name: Build and release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - run: npm ci

      - run: npm run build

      - run: npm run deb

      - uses: actions/upload-artifact@v7
        with:
          name: deb-package
          path: ./*.deb

      - uses: softprops/action-gh-release@v2
        with:
          files: ./*.deb
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
