name: Build and Release ARM64 .deb

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run build step
        run: npx build

      - name: Build .deb package
        run: npx node-deb

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ./*.deb

      - name: Create GitHub Release and upload .deb
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
